
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/sodium-platform-420519/github.com/krissendev/dockerintegrate:$SHORT_SHA ', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/sodium-platform-420519/github.com/krissendev/dockerintegrate:$SHORT_SHA']
