steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/dockerintegrate-app', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/dockerintegrate-app']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'dockerintegrate-app', '--image', 'gcr.io/$PROJECT_ID/dockerintegrate-app', '--region', 'europe-west1', '--platform', 'managed', '--allow-unauthenticated']

images:
- 'gcr.io/$PROJECT_ID/dockerintegrate-app'
options:
  logging: CLOUD_LOGGING_ONLY
